---
title: "Data 607 Week2"
author: "Shamecca Marshall"
date: "2023-09-11"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r}
library(kableExtra)
library(RMySQL)
```


```{undefined include=FALSE}
library(RMySQL)
library(RODBC)
library("dplyr")
library("dbplyr")
library(sqldf)
library(DBI)
library(weatherData)
```

# Connect to SQL
```{r warning=FALSE}
library(RODBC)
mysqlconnection = dbConnect(MySQL(),
                            dbname='movies',
                            host='localhost',
                            port=3306,
                            user='root',
                            password='root')

```

# Connect to database
```{r warning=FALSE}
myLocalPassword <- 'root'
my.database = dbConnect(MySQL(), user='root', password = myLocalPassword, dbname='movies', host='localhost')
dbListTables(my.database)
```

# Display Viewers

```{r warning=TRUE}
Viewers <- dbSendQuery(my.database, "SELECT * FROM viewers;")
dbFetch(Viewers)
```

# Display Movies

```{r}
Movies <- dbSendQuery(my.database, "SELECT * FROM movie;")
dbFetch(Movies)
```

# Display Rating Details

```{r}
RatingDetails <- dbSendQuery(my.database, "SELECT * FROM ratingdetails;")
dbFetch(RatingDetails)
```

# Display Movie Ratings

```{r}
MovieRatings <- dbSendQuery(my.database, "SELECT * FROM ratings;")
dbFetch(MovieRatings)
```
